rotate_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rotate_joint
    joint_speed: 1.17
    motor:
        id: 0
        init: 2208
        min: 1104
        max: 3377
pitch1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch1_joint
    joint_speed: 0.2
    motor:
        id: 1
        init: 3052
        min: 2402
        max: 3247
roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: roll_joint
    joint_speed: 0.3
    motor:
        id: 2
        init: 2013
        min: 1753
        max: 2272
pitch2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch2_joint
    joint_speed: 0.2
    motor:
        id: 3
        init: 2468
        min: 1883
        max: 2858
jaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: jaw_joint
    joint_speed: 0.2
    motor:
        id: 4
        init: 490
        min: 0
        max: 1039


#Pau2Motors config
pau2motors:
    topics:
        cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base
        cmd_eyes_pau: eyes_pitch;leye_yaw;reye_yaw
    motors:
      - name: eyes_pitch
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftPitch
          function:
            - name: linear
              min: 0.4
              max: -0.4
          hardware:
            name: pololu
            topic: /dmitry_eyes/cmd_pololu
            id: 2
            speed: 200
            acceleration: 100
        min: -0.58
        max: 1.117

      - name: leye_yaw
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftYaw
          function:
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: /dmitry_eyes/cmd_pololu
            id: 1
            speed: 200
            acceleration: 100
        min: -0.58
        max: 0.55

      - name: reye_yaw
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeRightYaw
          function:
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: /dmitry_eyes/cmd_pololu
            id: 0
            speed: 200
            acceleration: 100
        min: -0.68
        max: 0.45

    # ---Neck---

      - name: neck_pitch_bottom
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch1_controller/command
        min: -1
        max: 0.3

      - name: neck_pitch_top
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch2_controller/command
        min: -0.4
        max: 0.4

      - name: neck_roll
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: x
            - name: linear
              min: -0.4
              max: 0.4
          hardware:
            name: dynamixel
            topic: roll_controller/command
        min: -0.4
        max: 0.4

      - name: neck_base
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: y
            - name: linear
              scale: -1
              translate: 0
          hardware:
            name: dynamixel
            topic: rotate_controller/command
        min: -1.7
        max: 1.7