rotate_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rotate_joint
    joint_speed: 1.17
    motor:
        id: 0
        init: 2381
        min: 1358
        max: 3401
pitch1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch1_joint
    joint_speed: 0.2
    motor:
        id: 1
        init: 3460
        min: 3090
        max: 3725
roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: roll_joint
    joint_speed: 0.3
    motor:
        id: 2
        init: 1200
        min: 940
        max: 1400
pitch2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch2_joint
    joint_speed: 0.2
    motor:
        id: 3
        init: 2675
        min: 2376
        max: 3180
jaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: jaw_joint
    joint_speed: 0.2
    motor:
        id: 4
        init: 490
        min: 0
        max: 1039

#Pau2Motors config
pau2motors:
    topics:
        cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base
        cmd_eyes_pau: eyes_pitch;leye_yaw;reye_yaw
    motors:
      eyes_pitch:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftPitch
          function:
            - name: linear
              min: 0.4
              max: -0.4
          hardware:
            name: pololu
            topic: dmitry_eyes/cmd_pololu
            id: 2
            speed: 200
            acceleration: 100
        min: -0.58
        max: 1.117

      leye_yaw:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftYaw
          function:
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: dmitry_eyes/cmd_pololu
            id: 1
            speed: 200
            acceleration: 100
        min: -0.58
        max: 0.55

      reye_yaw:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeRightYaw
          function:
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: dmitry_eyes/cmd_pololu
            id: 0
            speed: 200
            acceleration: 100
        min: -0.68
        max: 0.45

    # ---Neck---

      neck_pitch_bottom:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch1_controller/command
        min: -1
        max: 0.3

      neck_pitch_top:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: -0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch2_controller/command
        min: -0.4
        max: 0.4

      neck_roll:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: x
            - name: linear
              min: -0.4
              max: 0.4
          hardware:
            name: dynamixel
            topic: roll_controller/command
        min: -0.4
        max: 0.4

      neck_base:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: y
            - name: linear
              scale: -1
              translate: 0
          hardware:
            name: dynamixel
            topic: rotate_controller/command
        min: -1.7
        max: 1.7